package agents

// Identities from Pi v0.85.1's parseSource/parseGitUrl and hosted-git-info 9.0.3.
// These fixtures keep parser compatibility tests independent of Node at runtime.
var piGitCases = []struct{ source, host, repo string }{
	{"git:git://github.com/ahmedelgabri/tmux-agent-panel", "github.com", "ahmedelgabri/tmux-agent-panel"},
	{"git://github.com/ahmedelgabri/tmux-agent-panel", "github.com", "ahmedelgabri/tmux-agent-panel"},
	{" git:  https://github.com/ahmedelgabri/tmux-agent-panel.git@main  ", "github.com", "ahmedelgabri/tmux-agent-panel"},
	{" https://github.com/ahmedelgabri/tmux-agent-panel ", "github.com", "ahmedelgabri/tmux-agent-panel"},
	{"\ufeffgit:\tgithub.com/ahmedelgabri/tmux-agent-panel\ufeff", "github.com", "ahmedelgabri/tmux-agent-panel"},
	{"\u0085git:github.com/ahmedelgabri/tmux-agent-panel", "", ""},
	{"git:ahmedelgabri/tmux-agent-panel", "github.com", "ahmedelgabri/tmux-agent-panel"},
	{"git:github:ahmedelgabri/tmux-agent-panel", "github.com", "ahmedelgabri/tmux-agent-panel"},
	{"git:github:ahmedelgabri/tmux-agent-panel@main", "github.com", "ahmedelgabri/tmux-agent-panel"},
	{"git:git+ssh://git@github.com/ahmedelgabri/tmux-agent-panel", "github.com", "ahmedelgabri/tmux-agent-panel"},
	{"git:git+https://github.com/ahmedelgabri/tmux-agent-panel", "github.com", "ahmedelgabri/tmux-agent-panel"},
	{"git:github.com:ahmedelgabri/tmux-agent-panel", "github.com", "ahmedelgabri/tmux-agent-panel"},
	{"git:git@github.com:ahmedelgabri/tmux-agent-panel", "github.com", "ahmedelgabri/tmux-agent-panel"},
	{"git:user@github.com:ahmedelgabri/tmux-agent-panel", "github.com", "ahmedelgabri/tmux-agent-panel"},
	{"git:https://github.com:ahmedelgabri/tmux-agent-panel", "github.com", "ahmedelgabri/tmux-agent-panel"},
	{"git:ssh://git@github.com:ahmedelgabri/tmux-agent-panel", "github.com", "ahmedelgabri/tmux-agent-panel"},
	{"git:https:github.com/ahmedelgabri/tmux-agent-panel", "github.com", "ahmedelgabri/tmux-agent-panel"},
	{"https://github.com/ahmedelgabri/tmux-agent-panel/", "github.com", "ahmedelgabri/tmux-agent-panel"},
	{"https://www.github.com/ahmedelgabri/tmux-agent-panel", "github.com", "ahmedelgabri/tmux-agent-panel"},
	{"https://GITHUB.COM/ahmedelgabri/tmux-agent-panel", "github.com", "ahmedelgabri/tmux-agent-panel"},
	{"ssh://git@GITHUB.COM/ahmedelgabri/tmux-agent-panel", "GITHUB.COM", "ahmedelgabri/tmux-agent-panel"},
	{"https://github.com/AhmedElGabri/tmux-agent-panel", "github.com", "AhmedElGabri/tmux-agent-panel"},
	{"https://github.com/ahmedelgabri/tmux-agent-panel/tree/main", "github.com", "ahmedelgabri/tmux-agent-panel"},
	{"https://github.com/ahmedelgabri/tmux-agent-panel/tree/main/folder%FF", "github.com", "ahmedelgabri/tmux-agent-panel"},
	{"https://github.com/ahmedelgabri/tmux-agent-panel/issues", "github.com", "ahmedelgabri/tmux-agent-panel/issues"},
	{"https://github.com/ahmedelgabri/tmux-agent-panel@", "github.com", "ahmedelgabri/tmux-agent-panel@"},
	{"https://github.com/ahmedelgabri/tmux-agent-panel#main", "github.com", "ahmedelgabri/tmux-agent-panel"},
	{"https://github.com/ahmedelgabri/tmux-agent-panel@feature/foo", "github.com", "ahmedelgabri/tmux-agent-panel"},
	{"https://github.com/ahmedelgabri/tmux-agent-panel?x=y#main", "github.com", "ahmedelgabri/tmux-agent-panel"},
	{"https://github.com:443/ahmedelgabri/tmux-agent-panel", "github.com", "ahmedelgabri/tmux-agent-panel"},
	{"https://token@github.com/ahmedelgabri/tmux-agent-panel", "github.com", "ahmedelgabri/tmux-agent-panel"},
	{"ssh://user@github.com:22/ahmedelgabri/tmux-agent-panel", "github.com", "ahmedelgabri/tmux-agent-panel"},
	{"https://github.com/ahmedelgabri/tmux%2Dagent-panel", "github.com", "ahmedelgabri/tmux-agent-panel"},
	{"https://github.com/ahmedelgabri/tmux-agent-panel.git.git", "github.com", "ahmedelgabri/tmux-agent-panel"},
	{"https://github.com/ahmedelgabri/tmux-agent-panel.git.git#%FF", "github.com", "ahmedelgabri/tmux-agent-panel.git"},
	{"git:github:ahmedelgabri/tmux-agent-panel.git.git", "github.com", "ahmedelgabri/tmux-agent-panel"},
	{"git:github.com/ahmedelgabri/tmux-agent-panel.git.git", "github.com", "ahmedelgabri/tmux-agent-panel"},
	{"git:github.com/ahmedelgabri/tmux-agent-panel@", "github.com", "ahmedelgabri/tmux-agent-panel@"},
	{"git:github:ahmedelgabri/tmux-agent-panel/", "github.com", "ahmedelgabri/tmux-agent-panel/"},
	{"https://github.com/other/../ahmedelgabri/tmux-agent-panel", "github.com", "ahmedelgabri/tmux-agent-panel"},
	{"git:git@github.com:other/../ahmedelgabri/tmux-agent-panel", "github.com", "ahmedelgabri/tmux-agent-panel"},
	{"https://github.com/ahmedelgabri%2F/tmux-agent-panel", "github.com", "ahmedelgabri//tmux-agent-panel"},
	{"https://github.com/ahmedelgabri/tmux-agent-panel/../other", "github.com", "ahmedelgabri/other"},
	{"git:github.com/ahmedelgabri/tmux-agent-panel%2F..", "", ""},
	{"git:github.com/ahmedelgabri/tmux-agent-panel%252F..", "", ""},
	{"git:github.com/ahmedelgabri/tmux-agent-panel%00", "", ""},
	{"git:github.com/ahmedelgabri/tmux-agent-panel%5C..", "", ""},
	{"git:github.com/ahmedelgabri/tmux-agent-panel%", "", ""},
	{"git:github.com/ahmedelgabri/tmux-agent-panel%FF", "", ""},
	{"git:github.com/ahmedelgabri/tmux-agent-panel.git#%FF", "", ""},
	{"git:https://github.com/ahmedelgabri/tmux-agent-panel.git%", "", ""},
	{"git:https://github.com.evil.example/ahmedelgabri/tmux-agent-panel", "github.com.evil.example", "ahmedelgabri/tmux-agent-panel"},
	{"git:https://github.com@evil.example/ahmedelgabri/tmux-agent-panel", "evil.example", "ahmedelgabri/tmux-agent-panel"},
	{"git:https://evil.example/github.com/ahmedelgabri/tmux-agent-panel", "evil.example", "github.com/ahmedelgabri/tmux-agent-panel"},
	{"git:https://github.com:99999/ahmedelgabri/tmux-agent-panel", "", ""},
	{"git:ftp://github.com/ahmedelgabri/tmux-agent-panel", "", ""},
	{"git:git+http://github.com/ahmedelgabri/tmux-agent-panel", "", ""},
	{"git:git://GITHUB.COM/ahmedelgabri/tmux-agent-panel", "GITHUB.COM", "ahmedelgabri/tmux-agent-panel"},
	{"git:git@GITHUB.COM:ahmedelgabri/tmux-agent-panel", "github.com", "ahmedelgabri/tmux-agent-panel"},
	{"git:github:ahmedelgabri/tmux-agent-panel@", "github.com", "null/"},
	{"git:github:tmux-agent-panel", "github.com", "null/tmux-agent-panel"},
	{"git:gitlab:user@github.com:ahmedelgabri/tmux-agent-panel", "gitlab.com", "github.com:ahmedelgabri/tmux-agent-panel"},
	{"git:bitbucket:user@github.com:ahmedelgabri/tmux-agent-panel", "bitbucket.org", "github.com:ahmedelgabri/tmux-agent-panel"},
	{"git:gist:user@github.com:ahmedelgabri/tmux-agent-panel", "gist.github.com", "github.com:ahmedelgabri/tmux-agent-panel"},
	{"git:sourcehut:user@github.com:ahmedelgabri/tmux-agent-panel", "git.sr.ht", "github.com:ahmedelgabri/tmux-agent-panel"},
	{"git:gitlab:x@bad%FF@github.com:ahmedelgabri/tmux-agent-panel", "github.com", "ahmedelgabri/tmux-agent-panel"},
	{"git:github:/", "github.com", "null/"},
	{"git:git@github.com:ahmedel\ngabri/tmux-agent-panel@", "", ""},
	{"git:", "", ""},
	{"", "", ""},
	{"github.com/ahmedelgabri/tmux-agent-panel", "", ""},
	{"git@github.com:ahmedelgabri/tmux-agent-panel", "", ""},
	{"github:ahmedelgabri/tmux-agent-panel", "", ""},
	{"ahmedelgabri/tmux-agent-panel", "", ""},
	{"git+ssh://git@github.com/ahmedelgabri/tmux-agent-panel", "", ""},
	{"HTTPS://github.com/ahmedelgabri/tmux-agent-panel", "", ""},
}
